//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using ZetaTrading.Adapters.WebApi.Common;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace ZetaTrading.Adapters.WebApi.TreeNodes
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class TreeNodeControllerBase : Microsoft.AspNetCore.Mvc.Controller
    {
        /// <remarks>
        /// Create a new node in your tree. You must to specify a parent node ID that belongs to your tree. A new node name
        /// <br/>must be unique across all siblings.
        /// </remarks>
        /// <param name="treeName">Tree name.</param>
        /// <param name="parentNodeId">Parent node id.</param>
        /// <param name="nodeName">Node name.</param>
        /// <returns>OK.</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api.user.tree.node.create")]
        public abstract System.Threading.Tasks.Task Create([Microsoft.AspNetCore.Mvc.FromQuery] string treeName, [Microsoft.AspNetCore.Mvc.FromQuery] long parentNodeId, [Microsoft.AspNetCore.Mvc.FromQuery] string nodeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <remarks>
        /// Delete an existing node in your tree. You must specify a node ID that belongs your tree.
        /// </remarks>
        /// <param name="treeName">Tree name.</param>
        /// <param name="nodeId">Node id.</param>
        /// <returns>OK.</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api.user.tree.node.delete")]
        public abstract System.Threading.Tasks.Task Delete([Microsoft.AspNetCore.Mvc.FromQuery] string treeName, [Microsoft.AspNetCore.Mvc.FromQuery] long nodeId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <remarks>
        /// Rename an existing node in your tree. You must specify a node ID that belongs your tree. A new name of the node
        /// <br/>must be unique across all siblings.
        /// </remarks>
        /// <param name="treeName">Tree name.</param>
        /// <param name="nodeId">Node id.</param>
        /// <param name="newNodeName">New node name.</param>
        /// <returns>OK.</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api.user.tree.node.rename")]
        public abstract System.Threading.Tasks.Task Rename([Microsoft.AspNetCore.Mvc.FromQuery] string treeName, [Microsoft.AspNetCore.Mvc.FromQuery] long nodeId, [Microsoft.AspNetCore.Mvc.FromQuery] string newNodeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

    }

    


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603